### ISSUE TITLE
page order changed

### ISSUE THREAD

**Issue by ilanc** [ffalt/pdf.js-extract#16]
Howdy,
I recently upgraded from 0.1.1 to 0.1.3 and have found that it extracts pages in a different order on some pdfs. Have you encountered this? is it a pdf.js-extract issue (e.g. `lib/index.js`) or `pdf.js` itself?

I've just tested, and 0.1.2 has the same page ordering. What commitId corresponds to v0.1.2?

**Comment by ffalt** [comment]
Hi, 

pdf.js version changed from 0.1.1 to 0.1.2, but it's pdf.js-extract calling for each page.

My first suspicion was [Promise handling](https://github.com/ffalt/pdf.js-extract/commit/0f34967316d42c0c0a04afd2b7a11486026980be#diff-6d186b954a58d5bb740f73d84fe39073), which changed from [0.1.2](https://github.com/ffalt/pdf.js-extract/commit/d9dcfc183d47d8f8798abd415168461aaa6ad80b) to 0.1.3. 
But according to the spec of Promise.all() the ascending order is preserved. This also showed a test with artificial slowing down the first page parsing. I was not able to produce an out of order result.

While I can just sort the pages result list to make sure, I rather would like to see the cause fixed. Would you please provide a sample pdf?

**Comment by ilanc** [comment]
That'll definitely be it. I'll share a pdf with you privately to test with.

BTW have you considered using git tags in order to tag published npm versions? e.g.
```sh
git tag 0.1.4
git push --tags
```

then you can see the code for the npm version in https://github.com/ffalt/pdf.js-extract/releases

**Comment by ffalt** [comment]
Ah, yes, thank you! 

Page objects are added to the list in the middle of processing. In fact, promise resolve results are not used at all. Should have noticed that before, but didn't. Async processing of pages is fine though, so I'm keeping it this way and just sort the result.

I'll start tagging the releases of pdf.js-extract as of now. [0.1.4](https://github.com/ffalt/pdf.js-extract/blob/master/CHANGELOG.md#014-20191230) is released.

**Comment by ilanc** [comment]
Thanks dude, I'll upgrade to 0.1.4 now and test.

**Comment by ilanc** [comment]
Perfect - working across all my unit tests!
