### ISSUE TITLE
Error: No "GlobalWorkerOptions.workerSrc" specified.

### ISSUE THREAD

**Issue by jp5525** [ffalt/pdf.js-extract#17]
Hello,

Im having an issue trying to use extractBuffer inside of a jest test. Any call results in the error 
`Error: No "GlobalWorkerOptions.workerSrc" specified.`

Ive even tried adding these 2 lines to lib/index.js file
`const worker = require("./pdfjs/pdf.worker.js");`
`pdfjsLib.GlobalWorkerOptions.workerSrc = worker`

which just results in a promise that never resolves.

Im kind of at a loss here any  insight would be appreciated.

Thanks

**Comment by ffalt** [comment]
Hi,

I switched the pdf.js-extract tests from mocha to jest and encoutered no issues. 

So my guess is, there are global variables in your test setup interfering with pdf.js. It seems to try to load the browser worker if e.g. ```window``` or ```Worker``` is globally defined. see e.g. [pdf.js#L9882](https://github.com/ffalt/pdf.js-extract/blob/03b4a180c514626147420e7c7c7de35d70128631/lib/pdfjs/pdf.js#L9882)
or [pdf.js#L11204](https://github.com/ffalt/pdf.js-extract/blob/03b4a180c514626147420e7c7c7de35d70128631/lib/pdfjs/pdf.js#L11204)

On node.js pdf.js is using a fake worker, AFAIK without using ```pdf.worker.js```.

Please check if you have defined global variables in your project or jest setup.

**Comment by perzanko** [comment]
I encountered same issue. I fixed it adding:

```
module.exports = {
  ...
  testEnvironment: "node"
}
```

to `jest.config.js`
