### ISSUE TITLE
Incomplete Extraction?

### ISSUE THREAD

**Issue by irtzasuhail** [ffalt/pdf.js-extract#18]
I am trying to extract individual words and their coordinates from a pdf file. I have tried it on a few files. On one of the files, it does the extraction perfectly. However, on the other file (which only has one line in it), it returns the entire sentence as a "word" without parsing out the individual words or their coordinates. I made this pdf myself by creating a file in Microsoft Word and exporting it as a pdf. Ive added a screenshot of what I get when I run 
`pdfExtract.extract(filePath, options, (err, data) => {
        if (err) {
            return console.log(err);
        }
        data.pages.forEach(function(page, index, object) {
            page.content.forEach(function(content, index, object) {
                console.log(content);
            });
        });
});`
<img width="256" alt="Screenshot 2020-02-11 at 15 51 31" src="https://user-images.githubusercontent.com/57505461/74253112-91c4bc00-4ce6-11ea-83c3-06bfb43a354d.png">

[5678.pdf](https://github.com/ffalt/pdf.js-extract/files/4186572/5678.pdf)

**Comment by ffalt** [comment]
Hi, I'm sorry, there is nothing I can do. 
[pdf.js](https://github.com/mozilla/pdf.js) returns blocks of text, not individual words.
There is an option _disableCombineTextItems_, but sadly it does not guarantee individual words neither.

**Comment by irtzasuhail** [comment]
Ah okay. Thank you for letting me know!
