### ISSUE TITLE
Get position / coordinates also for substrings / parts of the text-chunks extracted from the PDF-file?

### ISSUE THREAD

**Issue by christophscheuing** [ffalt/pdf.js-extract#24]
pdf.js-extract (and also pdf.js on its own) allow to get the x- and y-coordinates as well as the width and the height of the text chunks within the PDF-file. But is there any way to also get the coordinates of parts of these chunks, i.e. substrings of the str-String of the content items extracted via pdf.js(-extract)? This means that in the "Hello, world!"-example I would like to be able to know the x-coordinate of where "Hello" ends or where "world" starts?

Is there any way more comfortable than trying to calculate this via the width of the single characters of the given font?

The reason I'm trying to do this is that I want to search for a specific text in the PDF-file and find out its coordinates in order to be able to do something with it, draw a rectangle around it to highlight it for example. Any advice on how to achieve this would be welcome. Thanks in advance!

**Comment by ffalt** [comment]
Unfortunately, this is not possible for most pdfs.

https://github.com/mozilla/pdf.js/issues/13047
