### ISSUE TITLE
Coordinate system

### ISSUE THREAD

**Issue by enahsor** [ffalt/pdf.js-extract#29]
Is there a specific reason the coordinate system seems to be flipped? The Y axis runs from top to bottom while the X axis runs from left to right. You can see how initially this might be confusing to folks new to this package. Was there a specific reason why you opted to not have the axes share the same origin?

  0
  | Y
  |
  |
  |                      X
 ↓ -------------→
    0

**Comment by ffalt** [comment]
Hi, I did not chose the coordinate system. It's how pdf.js and IMHO the pdf format works. My best guess is: these are not mathematical coordinates. It's a document format, so it's kind of intutitve that it starts at the top.
