### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EhtQuyet** [ffalt/pdf.js-extract#32]
I try to pdfExtract.extract()
Message error: 'The `Array.prototype` contains unexpected enumerable properties: clone, last, first, max, min, insert; thus breaking e.g. `for...in` iteration of `Array`s.',

**Comment by ffalt** [comment]
Please provide a minimum of information for me to help you. Which node.js version are you using? What is your build setup? Where in the code does the Error occur.

Feel free to reopen an issue.
