### ISSUE TITLE
Setting up fake worker failed: "Cannot find module './vendors~pdfjsWorker.js'

### ISSUE THREAD

**Issue by nilamdhami** [ffalt/pdf.js-extract#36]
Getting this while trying to use pdf.js-extract npm library from NodeJS. Using it to extract text from PDF from backend

**Comment by ffalt** [comment]
There is no file named 'vendors~pdfjsWorker.js' in this package. 
Do you have more information? NodeJS version, full error log?

**Comment by nilamdhami** [comment]
@ffalt I'm trying to use this library on server side, so getting the issue of worker no setup

**Comment by ffalt** [comment]
Please try the current version 0.2.0 and see if it is still occuring. 

If yes, please post the exact nodejs version you are using on the server.

**Comment by nilamdhami** [comment]
Was using the webpack which was not compatible with the current version 0.2.0 of pdf.js-extract.

Resolved the issue with configuring the library in different repository and calling the lambda in my serverless Application.

**Comment by danrasmuson** [comment]
I found a fairly hacky way to get this to work without changing any of my webpack code... 

```javascript
import { PDFExtract } from "pdf.js-extract";
import * as pdfjs from "pdf.js-extract/lib/pdfjs/pdf.js";

// Hack to tell webpack to load the module
import * as pdfjsWorker from "pdf.js-extract/lib/pdfjs/pdf.worker.js";
pdfjsWorker

// Link the src with pdfjs to resolve loading the worker
pdfjs.GlobalWorkerOptions.workerSrc = "pdf.js-extract/lib/pdfjs/pdf.worker.js";
```

Copy and paste on my fellow Githubers!

**Comment by mr-chandan** [comment]
@danrasmuson it is working properly in my next app locally but gives me a error when u deploy to vercel how do I configure it 

Thank you

**Comment by PeterPilley** [comment]
If anyone comes back here to try and get this working 

`
const pdfjs = require('pdf.js-extract/lib/pdfjs/pdf');
pdfjs.GlobalWorkerOptions.workerSrc = '../node_modules/pdf.js-extract/lib/pdfjs/pdf.worker.js';
`

**Comment by travisdmathis** [comment]
if anyone is coming here with the same issue but with Svelte + Vercel here's the fix

```javascript
import { PDFExtract } from 'pdf.js-extract';
import * as pdfjs from 'pdf.js-extract/lib/pdfjs/pdf.js';
const pdfjsWorker = import('pdf.js-extract/lib/pdfjs/pdf.worker.js');

// Link the src with pdfjs to resolve loading the worker
async function setupPDFWorker() {
	await pdfjsWorker;
	if (pdfjs.GlobalWorkerOptions) {
		pdfjs.GlobalWorkerOptions.workerSrc = 'pdf.js-extract/lib/pdfjs/pdf.worker.js';
	} else {
		console.warn('pdfjs.GlobalWorkerOptions is not available');
	}
}

await setupPDFWorker();
```
