### ISSUE TITLE
In-the-middle word breaking on diacritics

### ISSUE THREAD

**Issue by janswist** [ffalt/pdf.js-extract#37]
I have such output:
```
[
>    {
>      x: 214.17,
>      y: 83.52999999999997,
>      str: 'PE',
>      dir: 'ltr',
>      width: 10.005,
>      height: 7.5,
>      fontName: 'Helvetica'
>    },
>    {
>      x: 224.18,
>      y: 83.52999999999997,
>      str: 'ŁNOMOCNICTWO / ',
>      dir: 'ltr',
>      width: 72.47999999999999,
>      height: 7.5,
>      fontName: 'g_d0_f1'
>    }]
```
It's supposed to be found as one word, but seems like library is breaking it into two treating it as a special symbol. Any way to get around this issue? Should be 'PEŁNOMOCNICTWO' as one word.

Same with other words that include diacritics.

**Comment by ffalt** [comment]
Yes, pdf.js does that, depending on the pdf with latin characters too. 
Unfortunatly I don't know a way to get around. AFAIK pdf.js does not know about words, but merges chars into words with a heuristic. https://github.com/mozilla/pdf.js/issues/12509#issuecomment-713906133
You may have to write your own postprocessing heuristic to merge it yourself.

**Comment by janswist** [comment]
I managed it by concatenating words like this:
`(firstWordX + firstWordLength) - nextWordX < 1`

So if the difference is lower than 1px it means this is the same word
