### ISSUE TITLE
Extract Arabic Words from PDF

### ISSUE THREAD

**Issue by SirPhemmiey** [ffalt/pdf.js-extract#39]
Hi, this library is cool. But how can i extract arabic texts as a whole just like ordinary characters??

I'd appreciate any leads on this. 

Thanks.

**Comment by ffalt** [comment]
Hi! I would need more information about this. Do you have an example pdf file or show how the current result looks like.

A wild guess (since it is a common problem with pdf) is that the included font in the pdf does not contain the needed information to extract as text.

**Comment by SirPhemmiey** [comment]
[10967791772.pdf](https://github.com/ffalt/pdf.js-extract/files/10235283/10967791772.pdf)

Hi @ffalt , yes this is a sample file

**Comment by ffalt** [comment]
So I ran it. Unfortunately I can't read arabic, so you please need to help me detecting what is wrong.

<img width="1161" alt="extract" src="https://user-images.githubusercontent.com/3438714/207823387-8c4e53a7-fa63-4d18-beb7-9757688a30cd.png">

**Comment by SirPhemmiey** [comment]
@ffalt can i get the result in json? I think it'll be easier to work with programmatically that way

**Comment by SirPhemmiey** [comment]
<img width="959" alt="Screenshot 2022-12-15 at 14 30 37" src="https://user-images.githubusercontent.com/22390818/207836478-488cf9d5-1297-44d5-9cfb-6be8c1af8d29.png">
Yes, i got that result in json but there's a problem with that. Have a look at the "str" value. It's like it kinda split the arabic texts and this way, it doesn't give/have any meaning

**Comment by SirPhemmiey** [comment]
Yeah, it doesn't work as intended
