### ISSUE TITLE
Is there a way to determine styles of the text? 

### ISSUE THREAD

**Issue by Jsnxyz** [ffalt/pdf.js-extract#4]
I need to extract some relevant text which are mostly bold in the pdf. But I do not find an obvious way where it indicates if the text is bold or has any other styles applied to it. Would be nice if it could have that.

**Comment by ffalt** [comment]
I created a test pdf, with two texts "Normal" and "Bold", the only difference in the pdf.js result is the font name
```json
{
	"x": 57,
	"y": 67.88999999999999,
	"str": "Normal",
	"dir": "ltr",
	"width": 38.6712,
	"height": 12,
	"fontName": "g_d0_f1"
},
{
	"x": 57,
	"y": 81.88999999999999,
	"str": "Bold",
	"dir": "ltr",
	"width": 26.6736,
	"height": 12,
	"fontName": "g_d0_f2"
},
```
There seems to be [undocumented](https://stackoverflow.com/questions/40656289/pdf-js-get-info-about-embedded-fonts) API for getting more information about fontNames, but additional parsing would be required.
So, unfortunatelly only the fontName is currently available as an indicator.
