### ISSUE TITLE
Setting up fake worker failed

### ISSUE THREAD

**Issue by leonardolombardi07** [ffalt/pdf.js-extract#43]
Hi! First of all, thank you for your library.

I'm using Next.js and using the pdf.js-extract library on the pages/api folder.
It works perfectly on development, but it crashes on production with the following error: 

``
Setting up fake worker failed: "Cannot find module './pdf.worker.js' Require stack: - /var/task/node_modules/pdf.js-extract/lib/pdfjs/pdf.js - /var/task/node_modules/pdf.js-extract/lib/cmap-reader.js - /var/task/node_modules/pdf.js-extract/lib/index.js - /var/task/.next/server/pages/api/notas-fiscais/extract.js - /var/task/node_modules/next/dist/server/next-server.js - /var/task/___next_launcher.cjs".
``

This is my package.json:

``
{
  "name": "rbna-automations",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "18.15.11",
    "@types/react": "18.0.35",
    "@types/react-dom": "18.0.11",
    "devextreme": "22.2.5",
    "devextreme-react": "22.2.5",
    "eslint": "8.38.0",
    "eslint-config-next": "13.3.0",
    "mindee": "^3.7.3",
    "multiparty": "^4.2.3",
    "next": "13.3.0",
    "openai": "^3.2.1",
    "pdf.js-extract": "^0.2.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "5.0.4",
    "xlsx": "https://cdn.sheetjs.com/xlsx-0.19.3/xlsx-0.19.3.tgz"
  },
  "devDependencies": {
    "@types/multiparty": "^0.0.33"
  }
}
``

I found this thread: [https://github.com/mozilla/pdf.js/issues/12066](https://github.com/mozilla/pdf.js/issues/12066), but couldn't figure it out how to fix the problem on the context of pdf.js-extract.

Thank you very much!

**Comment by ffalt** [comment]
Hi, there seems to be a incompatibly with some build setups (webpack?) 
Sorry, unfortunatly I don't have the time to investigate myself, please have a look at https://github.com/ffalt/pdf.js-extract/issues/36 for possible workarounds.

**Comment by sujjeee** [comment]
Hey @leonardolombardi07  did you find any way to use this library in nextjs? I'm also using it in Next.js and getting 'canvas' not found. How can I fix this? Also, did you manage to make it work in production?
