### ISSUE TITLE
Windows Print pdf extract

### ISSUE THREAD

**Issue by PapVasilis** [ffalt/pdf.js-extract#48]
Hello!
First of all great work!
I encountered an issue extracting data from a pdf download from print dialog. In metadata the producer is "Microsoft: Print To PDF". I did not have any issues with any other producer types such as "iText 4.2.0 by 1T3XT". 
Is there any solution?
I am using PDFExtract class, extract method and get every pages content.
Version: "pdf.js-extract": "^0.2.1"

Thanks,
Vasilis

**Comment by ffalt** [comment]
Hi!
You didn't say what the actual issues you encountered. 

No text? Then probably the PDF contains the text as pictures, which this library can't extract.
Scrambeld text? Then probably fonts are not included into the document, which could cause issues.
