### ISSUE TITLE
Is it Angular 6 ready?

### ISSUE THREAD

**Issue by deekj** [ffalt/pdf.js-extract#5]
When using in Angular 6, getting these error during compilation. Any idea, how to resolve it?

ERROR in ./node_modules/pdf.js-extract/lib/pdfjs/pdf.js
Module not found: Error: Can't resolve 'http' in 'F:\.........\node_modules\pdf.js-extract\lib\pdfjs'
ERROR in ./node_modules/pdf.js-extract/lib/pdfjs/pdf.js
Module not found: Error: Can't resolve 'https' in 'F:\.........\node_modules\pdf.js-extract\lib\pdfjs'

Thanks,
-Deepak

**Comment by ffalt** [comment]
Hi, sorry, no it's not. This is a nodejs module. Please have a look at the original https://github.com/mozilla/pdf.js for usage in a browser.
