### ISSUE TITLE
normalizeWhitespace parameter for getTextContent() option

### ISSUE THREAD

**Issue by alexschwantes** [ffalt/pdf.js-extract#7]
Can we expand the options so that getTextContent() can run with the normalizeWhitespace parameter?
https://github.com/ffalt/pdf.js-extract/blob/b1babe141b6c223f2d1cc208a7d80c517eeb4511/lib/index.js#L66

so it would look like :
```
const normalizeWhitespaceParam = options && options.normalizeWhitespace === true ? true : false;
return page.getTextContent({ normalizeWhitespace: normalizeWhitespaceParam }).then(function (content) {	
```

source: https://github.com/mozilla/pdf.js/blob/b2e7d0c89b76e228e49c7cee759873322a442f62/src/display/api.js#L779
thanks

**Comment by ffalt** [comment]
Done in [v0.1.0](https://www.npmjs.com/package/pdf.js-extract/v/0.1.0)
I had no idea such options existed, thanks for bringing it to my attention. 
Also included disableCombineTextItems. (both are now documented in the [README](https://github.com/ffalt/pdf.js-extract#options))

**Comment by alexschwantes** [comment]
awesome, thanks!
