### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by hl-a-k** [ffalt/pdf.js-extract#8]
The output of parsing of my pdf file is missing lots of information.
[201800000893524691.pdf](https://github.com/ffalt/pdf.js-extract/files/2572137/201800000893524691.pdf)

**Comment by ffalt** [comment]
Hi! I've added support for character maps in [v0.1.1](https://www.npmjs.com/package/pdf.js-extract/v/0.1.1), which are needed for pdf files like yours. 

Please update to the new version and the missing strings for text for the fonts STSong, SimSun & SimHei will be included in the output.

**Comment by hl-a-k** [comment]
awesome, thanks
